---
server:
    install: '1'
    packages: [vim, git]
    timezone: UTC
    locale: en_US.UTF-8
nginx:
    install: '1'
    docroot: /var/www/ov
    servername: onversus.com
mysql:
    install: '1'
    root_password: root
    database: db
    user: db_user
    password: db_pass
    dump: ''
redis:
    install: '1'
    port: '6379'
php:
    install: '1'
    ppa: php5-5.6
    packages: [php5-cli, php5-intl, php5-mcrypt, php5-mysql, php5-curl]
composer:
    install: '1'

